sudo: false
language: php

matrix:
  include:
    - php: 7.1
      dist: bionic
      env: DEPENDENCIES='low'
    - php: 7.2
      dist: bionic
      env: DEPENDENCIES='low'
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs' COMPOSER_FORCE='phpunit/phpunit ^9.0@dev'
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
 - composer self-update
 - composer install --prefer-source

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - vendor/bin/phpunit -c tests/phpunit.xml
  - cd ../

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
